#!/usr/bin/env node

var http = require('http');
var tequila = require('../index.js');  // Would be: require("passport-tequila") in your app

var tequilaJar = new tequila.plain();

var server = http.createServer(function (request, response) {
  if (request.url == "/restricted") {
    var authenticated = tequilaJar.authenticate(request, response);
    if (authenticated) {
      response.writeHead(200, {"Content-Type": "text/html"});
      response.end("<html><body><p>" +
      "<p>Demo Tequilified server: Restricted Zone\n</p>" +
      "<p>Welcome, " + authenticated.user + "!</p>");
    }
  } else {
    response.writeHead(200, {"Content-Type": "text/html"});
    response.end("<html><body>" +
    "<p>Demo Tequilified server\n</p>" +
    "<p>Server is at: " + tequilaJar.server + "</p>" +
    '<p><a href="/restricted">Enter restricted area</a></p>' +
    "</body></html>");
  }
});

server.listen(process.env.PORT || 3000);

console.log('Demo server listening on port ' + server.address().port);
