#!/usr/bin/env node

var http = require('http');
var tequila = require('passport-tequila');

// FIXME WORK IN PROGRESS - This doesn't actually work.
var tequilaJar = new tequila.Standalone();

var server = http.createServer(function (request, response) {
  if (request.url == "/restricted") {
    tequilaJar.authenticate(request, response,
        function (session) {  // onSuccess
          response.writeHead(200, {"Content-Type": "text/html"});
          response.end("<html><body><p>" +
          "<p>Demo Tequilified server: Restricted Zone\n</p>" +
          "<p>Welcome, " + session.user + "!</p>");
        },
        {onRejected: function () {
          response.writeHead(500, {"Content-Type": "text/html"});
          response.end('<html><body><p style="font-color: red;">No access</p></body></html>');
        }});
  } else {
    response.writeHead(200, {"Content-Type": "text/html"});
    response.end("<html><body>" +
    "<p>Demo Tequilified server\n</p>" +
    "<p>Server is at: " + tequilaJar.server + "</p>" +
    '<p><a href="/restricted">Enter restricted area</a></p>' +
    "</body></html>");
  }
});

server.listen(process.env.PORT || 3000);

console.log('Demo server listening on port ' + server.address().port);
